<a href="https://colab.research.google.com/github/ayushi-006/Hands_on_Pandas-/blob/main/PANDAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#**PANDAS**
pandas is a versatile python library that is maily used to simplify the task of data manipulation.
Pandas lib is primarily used in conjunction with other libraries which are used for DataScience

##Things we can do by the help of PANDAS

*  Data set cleaning, merging, and joining
*  Easy handling of missing data.
*  Columns can be inserted and deleted from DataFrame and higher-dimensional
   objects.
*  Powerful group by functionality for performing split-apply-combine    
   operations on data sets.
*  Data Visualization.

The primary Data Structure in ***pandas*** are implemented in two classes
*  **DataFrame** :  Two-dimensional data structure with labeled axes, DF can be
      created using lists, dictionary etc.
*  **Series** :  One-dimensional array-like object that can hold data of any
      type. Series is a basic building block of python DataFrame.

``` Import Pandas library```

In [ ]:
import pandas as pd
pd.__version__

'2.0.3'

```we are currently working on **Pandas version 2.0.3**```

now we will import the data from sklearn library to work on it

In [ ]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes(as_frame = True)
print(type(diabetes["data"]))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
#loding the data into dataframe

df = diabetes["data"]

another way of creating a dataframe from series


In [ ]:
cities = pd.Series(["mumbai" , "delhi", "bangalore", "chennai"])
population = pd.Series(["100000" , "NaN" , "300000","400000"])

city_info =pd.DataFrame({"cities":cities, "population":population})

In [ ]:
city_info


cities population
0     mumbai     100000
1      delhi        NaN
2  bangalore     300000
3    chennai     400000

In [ ]:
print(type(city_info))


<class 'pandas.core.frame.DataFrame'>


##Exploring data in DataFrame

In [ ]:
#to get first 5 rows of the whole data
df.head()


age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

In [ ]:
#to get last 5 rows of whole data
df.tail()

#df.tail(10) , to get first 10 rows

age       sex       bmi        bp        s1        s2        s3  \
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064

In [ ]:
df.shape

(442, 10)

```data hai total 442 rows and 10 columns```

In [ ]:
df.columns
 # name of the 10 columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [ ]:
df.describe()
#describing the data statistically

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17  
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01  
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02  
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03  
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02  
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01

In [ ]:
# to change the perecentiles

df.describe(percentiles=[0.2 , 0.6 , 0.8]).T
# ".T" to get the transposed view of the data

count          mean       std       min       20%       50%       60%  \
age  442.0 -2.511817e-19  0.047619 -0.107226 -0.045472  0.005383  0.016281   
sex  442.0  1.230790e-17  0.047619 -0.044642 -0.044642 -0.044642  0.050680   
bmi  442.0 -2.245564e-16  0.047619 -0.090275 -0.040480 -0.007284  0.005219   
bp   442.0 -4.797570e-17  0.047619 -0.112399 -0.040099 -0.005670  0.008101   
s1   442.0 -1.381499e-17  0.047619 -0.126781 -0.038720 -0.004321  0.008063   
s2   442.0  3.918434e-17  0.047619 -0.115613 -0.036950 -0.003819  0.008707   
s3   442.0 -5.777179e-18  0.047619 -0.102307 -0.039719 -0.006584  0.008142   
s4   442.0 -9.042540e-18  0.047619 -0.076395 -0.039493 -0.002592 -0.002592   
s5   442.0  9.293722e-17  0.047619 -0.126097 -0.041176 -0.001947  0.012551   
s6   442.0  1.130318e-17  0.047619 -0.137767 -0.038357 -0.001078  0.007207   

          80%       max  
age  0.041708  0.110727  
sex  0.050680  0.050680  
bmi  0.042296  0.170555  
bp   0.049415  0.132044  
s1   0.039434  0.153914  
s2   0.039521  0.198788  
s3   0.037595  0.181179  
s4   0.034309  0.185234  
s5   0.038853  0.133597  
s6   0.036201  0.135612

In [ ]:
df.info()
# information about the datatype, null & not_notnull content

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


```now we are aware of the statistical summary of the data```

#**Data Selection**


In [ ]:
#prints the names of all the columns
print(df.columns)
#datatype of columns
type(df.columns)

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')


pandas.core.indexes.base.Index

In [ ]:
df['age']
#prints all 442 rows of 'age' col

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...   
437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, Length: 442, dtype: float64

In [ ]:
print(type(df['age']))
#datatype of age column i.e. Series

<class 'pandas.core.series.Series'>


In [ ]:
df['age'][0]
#prints the 0th entry of 'AGE'

0.038075906433423026

In [ ]:
df['age'][0:5]
#prints the first 5 entries of 'AGE'

0    0.038076
1   -0.001882
2    0.085299
3   -0.089063
4    0.005383
Name: age, dtype: float64

In [ ]:
df[['age','sex']][:5]

age       sex
0  0.038076  0.050680
1 -0.001882 -0.044642
2  0.085299  0.050680
3 -0.089063 -0.044642
4  0.005383 -0.044642

In [ ]:
df['age'][-5:]
#prints last 5 rows

437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, dtype: float64

In [ ]:
df[['age','sex']][-5:]


age       sex
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

Two important function
*  ``` .loc``` :   Location, prints the row whole location is provided
*  ``` .iloc``` : Integer Location,

In [ ]:
df.loc[5]

age   -0.092695
sex   -0.044642
bmi   -0.040696
bp    -0.019442
s1    -0.068991
s2    -0.079288
s3     0.041277
s4    -0.076395
s5    -0.041176
s6    -0.096346
Name: 5, dtype: float64

In [ ]:
df.iloc[5
        ]

age   -0.092695
sex   -0.044642
bmi   -0.040696
bp    -0.019442
s1    -0.068991
s2    -0.079288
s3     0.041277
s4    -0.076395
s5    -0.041176
s6    -0.096346
Name: 5, dtype: float64

The basic difference between ```.loc``` and ```.iloc``` is that ▶
```.iloc``` always starts its counting from 0
```.loc``` prints out the result which is asked for

This function is basically used to get details/info about a particular row

In [ ]:
df.head(n=7)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
5 -0.092695 -0.044642 -0.040696 -0.019442 -0.068991 -0.079288  0.041277   
6 -0.045472  0.050680 -0.047163 -0.015999 -0.040096 -0.024800  0.000779   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641  
5 -0.076395 -0.041176 -0.096346  
6 -0.039493 -0.062917 -0.038357

In [ ]:
df.loc[5 , 'bmi']
#prints the information of desired column of a particular row

-0.040695940499992665

In [ ]:
df.loc[0:6,'age']

0    0.038076
1   -0.001882
2    0.085299
3   -0.089063
4    0.005383
5   -0.092695
6   -0.045472
Name: age, dtype: float64

In [ ]:
df.iloc[4, [3,4,5,7]]

bp    0.021872
s1    0.003935
s2    0.015596
s4   -0.002592
Name: 4, dtype: float64

In [ ]:
# df.loc[4, [3,4,5,7]
# this function with [.loc] will give error as, coulumns are indexed and, [.loc]
# does not support indexing.

In [ ]:
age_group = df.age >	-0.045472
age_group

0       True
1       True
2       True
3      False
4       True
       ...  
437     True
438     True
439     True
440    False
441    False
Name: age, Length: 442, dtype: bool

In [ ]:
age_range = df.loc[age_group]

In [ ]:
age_range.head(5)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
7  0.063504  0.050680 -0.001895  0.066629  0.090620  0.108914  0.022869   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
4 -0.002592 -0.031988 -0.046641  
7  0.017703 -0.035816  0.003064

In [ ]:
age_range.iloc[3 , [2,3]]

bmi   -0.036385
bp     0.021872
Name: 4, dtype: float64

In [ ]:
sex_bmi = df.loc[( df.age > 0.063504) & (df.bmi >-0.001895)	]
sex_bmi.head(5)

age       sex       bmi        bp        s1        s2        s3  \
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
17   0.070769  0.050680  0.012117  0.056301  0.034206  0.049416 -0.039719   
80   0.070769 -0.044642  0.012117  0.042529  0.071357  0.053487  0.052322   
154  0.067136  0.050680  0.020739 -0.005670  0.020446  0.026243 -0.002903   
167  0.070769 -0.044642  0.069241  0.037950  0.021822  0.001504 -0.036038   

           s4        s5        s6  
2   -0.002592  0.002861 -0.025930  
17   0.034309  0.027364 -0.001078  
80  -0.002592  0.025395 -0.005220  
154 -0.002592  0.008641  0.003064  
167  0.039106  0.077637  0.106617

In [ ]:
sex_bmi.shape

(21, 10)

Using NumPy

In [ ]:
import numpy as np

In [ ]:
DataFrame = pd.DataFrame(np.random.randn(10,5),index = list('1234567890'),columns = list('abcde'))
DataFrame


a         b         c         d         e
1  0.563524 -0.608019 -1.705134  0.500994  1.300743
2 -0.053050 -0.055842  1.327660  0.752268 -0.093017
3  0.343209  0.896600 -1.089488 -0.697787  0.580511
4 -0.360525 -0.134844  0.165292 -0.558139 -0.864505
5 -0.400031 -1.030999 -3.088939 -1.687800 -1.487117
6  0.440998  0.910536 -0.701083  0.490901 -0.693960
7  0.010092  0.045058 -0.904476 -1.122518  1.002120
8 -0.225098  0.192907 -0.006817 -0.888647  0.789604
9 -1.197088  1.597883 -0.163946 -0.123572  1.182958
0 -0.108190  0.492098 -1.057351 -0.220168 -0.479441

In [ ]:
index = list('abcdefghijklmn')
index

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']

In [ ]:
date = [1,2,3,4,5,6,7,8,9,0,]
date

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [ ]:
DataFrame.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
DataFrame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 1 to 0
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       10 non-null     float64
 1   b       10 non-null     float64
 2   c       10 non-null     float64
 3   d       10 non-null     float64
 4   e       10 non-null     float64
dtypes: float64(5)
memory usage: 480.0+ bytes


In [ ]:
DataFrame.loc['1' , ['b','c']]

b   -0.608019
c   -1.705134
Name: 1, dtype: float64

In [ ]:
DataFrame.loc['2':'5' , 'a':'d']

a         b         c         d
2 -0.053050 -0.055842  1.327660  0.752268
3  0.343209  0.896600 -1.089488 -0.697787
4 -0.360525 -0.134844  0.165292 -0.558139
5 -0.400031 -1.030999 -3.088939 -1.687800

In [ ]:
DataFrame.iloc[: ,4]

1    1.300743
2   -0.093017
3    0.580511
4   -0.864505
5   -1.487117
6   -0.693960
7    1.002120
8    0.789604
9    1.182958
0   -0.479441
Name: e, dtype: float64

###Lambda function ▶
It useful for simple operations that we don't want to define in a separate function and also provides a flexible and concise way to perform data transformations and analysis.


In [ ]:
selector = lambda DataFrame: DataFrame['a'] >0
selector

<function __main__.<lambda>(DataFrame)>

In [ ]:
DataFrame.loc[selector]

a         b         c         d         e
1  0.563524 -0.608019 -1.705134  0.500994  1.300743
3  0.343209  0.896600 -1.089488 -0.697787  0.580511
6  0.440998  0.910536 -0.701083  0.490901 -0.693960
7  0.010092  0.045058 -0.904476 -1.122518  1.002120

In [ ]:
selector = lambda DataFrame: DataFrame['a'] > 0.5
selector

<function __main__.<lambda>(DataFrame)>

In [ ]:
DataFrame.loc[selector]

a         b         c         d         e
1  0.563524 -0.608019 -1.705134  0.500994  1.300743

In [ ]:
selector = lambda DataFrame: (DataFrame['a'] > 0.5)&(DataFrame['b'] < 0.2)

In [ ]:
DataFrame.loc[selector]

a         b         c         d         e
1  0.563524 -0.608019 -1.705134  0.500994  1.300743

```another way of doing same thing without the *lambda function* and .loc```

In [ ]:
condition_for_selection = (DataFrame['a'] > 0.5)&(DataFrame['b'] < 0.2)
condition_for_selection
#only third row satisfies the criteria

1     True
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
0    False
dtype: bool

In [ ]:
#to print the 3rd row
DataFrame[condition_for_selection]

a         b         c         d         e
1  0.563524 -0.608019 -1.705134  0.500994  1.300743

using the ```OR``` ```{ | }``` operator

In [ ]:
or_operator = (DataFrame['a'] >1) | (DataFrame['b'] < 0.8)
or_operator

1     True
2     True
3    False
4     True
5     True
6    False
7     True
8     True
9    False
0     True
dtype: bool

using the ```not``` ```{ ~ }``` operator

In [ ]:
not_operator  = (DataFrame['a'] > -1) & ~(DataFrame['b'] < 2)
not_operator
# the & operator is used to combine  the two conditions

1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
0    False
dtype: bool

##How to ```drop()``` and modify rows and columns in a DataFrame

Creating a new column

In [ ]:
 DataFrame['f'] = DataFrame['a'] + DataFrame['b']
 DataFrame

a         b         c         d         e         f
1  0.563524 -0.608019 -1.705134  0.500994  1.300743 -0.044495
2 -0.053050 -0.055842  1.327660  0.752268 -0.093017 -0.108892
3  0.343209  0.896600 -1.089488 -0.697787  0.580511  1.239808
4 -0.360525 -0.134844  0.165292 -0.558139 -0.864505 -0.495369
5 -0.400031 -1.030999 -3.088939 -1.687800 -1.487117 -1.431030
6  0.440998  0.910536 -0.701083  0.490901 -0.693960  1.351535
7  0.010092  0.045058 -0.904476 -1.122518  1.002120  0.055151
8 -0.225098  0.192907 -0.006817 -0.888647  0.789604 -0.032191
9 -1.197088  1.597883 -0.163946 -0.123572  1.182958  0.400795
0 -0.108190  0.492098 -1.057351 -0.220168 -0.479441  0.383908

In [ ]:
 DataFrame['g'] = DataFrame['d']* 2
 DataFrame

a         b         c         d         e         f         g
1  0.563524 -0.608019 -1.705134  0.500994  1.300743 -0.044495  1.001988
2 -0.053050 -0.055842  1.327660  0.752268 -0.093017 -0.108892  1.504536
3  0.343209  0.896600 -1.089488 -0.697787  0.580511  1.239808 -1.395574
4 -0.360525 -0.134844  0.165292 -0.558139 -0.864505 -0.495369 -1.116279
5 -0.400031 -1.030999 -3.088939 -1.687800 -1.487117 -1.431030 -3.375601
6  0.440998  0.910536 -0.701083  0.490901 -0.693960  1.351535  0.981802
7  0.010092  0.045058 -0.904476 -1.122518  1.002120  0.055151 -2.245036
8 -0.225098  0.192907 -0.006817 -0.888647  0.789604 -0.032191 -1.777294
9 -1.197088  1.597883 -0.163946 -0.123572  1.182958  0.400795 -0.247144
0 -0.108190  0.492098 -1.057351 -0.220168 -0.479441  0.383908 -0.440336

 ### ▶ To replace the missing values or change the particular set of same values to another

In [ ]:
criteria = DataFrame['a'] < -0.2
criteria

1    False
2    False
3    False
4     True
5     True
6    False
7    False
8     True
9     True
0    False
Name: a, dtype: bool

In [ ]:
DataFrame.loc[criteria ,"a"] = 0
DataFrame

a         b         c         d         e         f         g
1  0.563524 -0.608019 -1.705134  0.500994  1.300743 -0.044495  1.001988
2 -0.053050 -0.055842  1.327660  0.752268 -0.093017 -0.108892  1.504536
3  0.343209  0.896600 -1.089488 -0.697787  0.580511  1.239808 -1.395574
4  0.000000 -0.134844  0.165292 -0.558139 -0.864505 -0.495369  0.000000
5  0.000000 -1.030999 -3.088939 -1.687800 -1.487117 -1.431030  0.000000
6  0.440998  0.910536 -0.701083  0.490901 -0.693960  1.351535  0.981802
7  0.010092  0.045058 -0.904476 -1.122518  1.002120  0.055151 -2.245036
8  0.000000  0.192907 -0.006817 -0.888647  0.789604 -0.032191  0.000000
9  0.000000  1.597883 -0.163946 -0.123572  1.182958  0.400795  0.000000
0 -0.108190  0.492098 -1.057351 -0.220168 -0.479441  0.383908 -0.440336

In [ ]:
#To change the values in the entire Dataset
criteria = DataFrame< -0.2

DataFrame[criteria] = 0
DataFrame

a         b         c         d         e         f         g
1  0.563524  0.000000  0.000000  0.500994  1.300743 -0.044495  1.001988
2 -0.053050 -0.055842  1.327660  0.752268 -0.093017 -0.108892  1.504536
3  0.343209  0.896600  0.000000  0.000000  0.580511  1.239808  0.000000
4  0.000000 -0.134844  0.165292  0.000000  0.000000  0.000000  0.000000
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
6  0.440998  0.910536  0.000000  0.490901  0.000000  1.351535  0.981802
7  0.010092  0.045058  0.000000  0.000000  1.002120  0.055151  0.000000
8  0.000000  0.192907 -0.006817  0.000000  0.789604 -0.032191  0.000000
9  0.000000  1.597883 -0.163946 -0.123572  1.182958  0.400795  0.000000
0 -0.108190  0.492098  0.000000  0.000000  0.000000  0.383908  0.000000

### ▶ To add a new column in the DataSet

In [ ]:
cities = [ 'Mumbai' , "lucknow" , "pune" , "banglore" , "chennai" , "gujrat" , "delhi" , "kerela" , "mp" , "goa"]
DataFrame['city'] = cities

In [ ]:
DataFrame_copy = DataFrame.copy()


In [ ]:
cities_new = [ 'Mumbai' , "lucknow" , "pune" , "banglore" , "chennai" , "gujrat" , "delhi" , "kerela" , "mp" , "goa"]
DataFrame_copy['new_city'] = cities_new
DataFrame_copy

a         b         c         d         e         f         g  \
1  0.563524  0.000000  0.000000  0.500994  1.300743 -0.044495  1.001988   
2 -0.053050 -0.055842  1.327660  0.752268 -0.093017 -0.108892  1.504536   
3  0.343209  0.896600  0.000000  0.000000  0.580511  1.239808  0.000000   
4  0.000000 -0.134844  0.165292  0.000000  0.000000  0.000000  0.000000   
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6  0.440998  0.910536  0.000000  0.490901  0.000000  1.351535  0.981802   
7  0.010092  0.045058  0.000000  0.000000  1.002120  0.055151  0.000000   
8  0.000000  0.192907 -0.006817  0.000000  0.789604 -0.032191  0.000000   
9  0.000000  1.597883 -0.163946 -0.123572  1.182958  0.400795  0.000000   
0 -0.108190  0.492098  0.000000  0.000000  0.000000  0.383908  0.000000   

       city    cities  new_city  
1    Mumbai    Mumbai    Mumbai  
2   lucknow   lucknow   lucknow  
3      pune      pune      pune  
4  banglore  banglore  banglore  
5   chennai   chennai   chennai  
6    gujrat    gujrat    gujrat  
7     delhi     delhi     delhi  
8    kerela    kerela    kerela  
9        mp        mp        mp  
0       goa       goa       goa

# SGD
Stochastic Gradient Descent


In [ ]:
for i in range(3):
  for j in range(3):
    for k in range(3):
      print(f"{i}{j}{k}")

000
001
002
010
011
012
020
021
022
100
101
102
110
111
112
120
121
122
200
201
202
210
211
212
220
221
222


In [ ]:
def goodbye():
  print("goodbye , world")
print("hello,world")
goodbye(

)


hello,world
goodbye , world


In [ ]:
def multiply(x,y):
  return x*y

print(multiply(2,3))
print(multiply(4,5))

6
20


In [ ]:
def pythagoras(a,b):
  if a<=0 or b <=0:
    return None
  return (a**2 + b**2)
num1 = int(input("enter the first number"))
num2 = int(input("enter the second number"))
if num2<0:
  print("The num is wrong")
else:
 print(pythagoras(num1,num2))

enter the first number5
enter the second number4
41


In [ ]:
def return3():
  return 2
x = 2**return3()
print(x)

4


In [ ]:
fruit = "oringe"
fruit[2] = "a"
print(fruit)

TypeError: 'str' object does not support item assignment

#**NUMPY**


In [4]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
print(type(a))
a[0] = 50 #numpy arrays are mutable
a

<class 'numpy.ndarray'>


array([50,  2,  3,  4])

In [7]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape
      )

(2, 4)


In [8]:
print(b[0,0] , b[1,1] ,b[1,2])

1 6 7


#numpy functions to create numpy arrays

In [9]:
b = np.zeros((2,3)) #to get the zero matrix of desired shape
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
c = np.ones((2,2)) #to get the ones matrix of desired shape
c

array([[1., 1.],
       [1., 1.]])

In [11]:
d = np.full((2,2),5) # to get the desired matrix of given number
d

array([[5, 5],
       [5, 5]])

In [12]:
e = np.eye(3) # to get the identity matrix of desired shape
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])